/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary.test;

//import org.junit.Test;
import basiclibrary.Library;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

        assertEquals(1,classUnderTest.roll(1).length);
        assertTrue(classUnderTest.containsDuplicates(new int[]{2,3,3,4}));
        assertEquals(2.5,classUnderTest.average(new int[]{2,2,2,1}));
        assertArrayEquals(new int[]{4,4,4,4},classUnderTest.lowAvg(new int[][]{{4,4,4,4},{3,3,3,3}}));
    }
}