//package basiclibrary;/*
// * This Java source file was generated by the Gradle 'init' task.
// */
//
//package basiclibrary;
//
//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;
//
//class LibraryTest {
//    @Test
//    void someLibraryMethodReturnsTrue() {
//        Library testing = new Library();
//
//        assertEquals(3, testing.roll(3).length);
//        assertTrue(testing.checkDuplicates(new int[]{2, 2, 3, 4}));
//        assertEquals(3, testing.simpleAvg(new int[]{2, 4}));
//        assertArrayEquals(new int[]{2, 4}, testing.minAvgOfArrOfArrays(new int[][]{{4, 4}, {2, 4}}));
//    }
//}

