/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;
 
public class Library {

    public static void main(String[] args) {

        Restaurant macDonalds = new Restaurant("macDonalds",4);
//        Restaurant KFC = new Restaurant("sara",2);

        //  Review method
        Review rev1 = new Review("good restaurant","mohammad",2);
//        Review rev2 = new Review("bad restaurant","sara",0);

        // 3- addReview method
        macDonalds.addReview(rev1);



        System.out.println(macDonalds.toString());
//        System.out.println(rev1.toString());

    }

}