/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {

        Restaurant macDonalds = new Restaurant("macDonalds",4);
//        Restaurant KFC = new Restaurant("sara",2);

        //  Review method
        Review rev1 = new Review("good restaurant","mohammad",2);
//        Review rev2 = new Review("bad restaurant","sara",0);

        // 3- addReview method
        macDonalds.addReview(rev1);



        System.out.println(macDonalds.toString());

//        System.out.println(rev1.toString());

        ///////////////////////////////

        Shop shop1 = new Shop("best movie","this shop for the best movie ",2);
        System.out.println(shop1.toString());
        Review review1 = new Review("good shop","mohammad",5);

        shop1.addReview(review1);
        System.out.println(shop1.toString());


        Theater theater1 = new Theater("rainbow theater");
//        System.out.println(theater1);

        theater1.addMovie("The Shawshank Redemption");
        theater1.addMovie(" Interstellar");
        theater1.addMovie(" Joker ");
        System.out.println(theater1.toString());

        theater1.removeMovie(" Joker ");
        System.out.println(theater1.toString());



        Review review = new Review("good","mohammad",5);

        theater1.addReview(review);
        System.out.println(review);
        System.out.println(theater1.toString());




    }

}