/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String path = "./app/src/main/resources/gates.js";
        linter(path);
//        File myObj = new File("./app/src/main/resources/gates.js");
//        Scanner myReader = new Scanner(myObj);
    }
    public static ArrayList<String> linter(String stringPath) {
        ArrayList<String> finalvalue = new ArrayList<String>();
        Path path = Paths.get(stringPath);
        try {
            List<String> fileLines = Files.readAllLines(path);
            int value = 1;

            for(String line : fileLines) {
                if (!line.endsWith(";") && !line.endsWith("}") && !line.endsWith("{") && !line.contains("else") && !line.contains("if") && !line.equals("")){
                    String printLine = "Line " + value + " : Missing semicolon.";
                    finalvalue.add(printLine);
                }
                value++;
            }
        } catch (IOException exception){
            System.out.println("An error occurred while reading from file");
        }
        return finalvalue;
    }
}