/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {
    @Test public void testLinter() {
        String testPath = "./src/test/resources/test.js";
        ArrayList<String> outList = new ArrayList<String>();
        outList.add("Line 9 : Missing semicolon.");
        outList.add("Line 11 : Missing semicolon.");
        System.out.println(outList.equals(App.linter(testPath)));
        assertEquals( outList ,App.linter(testPath));
    }
}